[2022-07-02 10:52:38,059] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: seed_postgres_db_dag.create_users_table manual__2022-07-02T10:52:36.829834+00:00 [queued]>
[2022-07-02 10:52:38,070] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: seed_postgres_db_dag.create_users_table manual__2022-07-02T10:52:36.829834+00:00 [queued]>
[2022-07-02 10:52:38,071] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-07-02 10:52:38,071] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-07-02 10:52:38,071] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-07-02 10:52:38,090] {taskinstance.py:1378} INFO - Executing <Task(PostgresOperator): create_users_table> on 2022-07-02 10:52:36.829834+00:00
[2022-07-02 10:52:38,095] {standard_task_runner.py:52} INFO - Started process 422 to run task
[2022-07-02 10:52:38,098] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'seed_postgres_db_dag', 'create_users_table', 'manual__2022-07-02T10:52:36.829834+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/seed_postgres_db_dag.py', '--cfg-path', '/tmp/tmpsn_5r1sb', '--error-file', '/tmp/tmpkme29fwx']
[2022-07-02 10:52:38,099] {standard_task_runner.py:80} INFO - Job 29: Subtask create_users_table
[2022-07-02 10:52:38,165] {task_command.py:370} INFO - Running <TaskInstance: seed_postgres_db_dag.create_users_table manual__2022-07-02T10:52:36.829834+00:00 [running]> on host a5e5aec483b5
[2022-07-02 10:52:38,251] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=seed_postgres_db_dag
AIRFLOW_CTX_TASK_ID=create_users_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-02T10:52:36.829834+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-02T10:52:36.829834+00:00
[2022-07-02 10:52:38,268] {base.py:68} INFO - Using connection ID 'postgres_conn' for task execution.
[2022-07-02 10:52:38,273] {dbapi.py:208} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL PRIMARY KEY
            );
            , parameters: None
[2022-07-02 10:52:38,275] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2022-07-02 10:52:38,296] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=seed_postgres_db_dag, task_id=create_users_table, execution_date=20220702T105236, start_date=20220702T105238, end_date=20220702T105238
[2022-07-02 10:52:38,350] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-02 10:52:38,402] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
