[2022-07-02 12:28:47,529] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: process_flowers_dag._process_flowers_data manual__2022-07-02T12:28:46.308083+00:00 [queued]>
[2022-07-02 12:28:47,547] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: process_flowers_dag._process_flowers_data manual__2022-07-02T12:28:46.308083+00:00 [queued]>
[2022-07-02 12:28:47,548] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-07-02 12:28:47,548] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-07-02 12:28:47,548] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-07-02 12:28:47,567] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): _process_flowers_data> on 2022-07-02 12:28:46.308083+00:00
[2022-07-02 12:28:47,573] {standard_task_runner.py:52} INFO - Started process 4001 to run task
[2022-07-02 12:28:47,578] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'process_flowers_dag', '_process_flowers_data', 'manual__2022-07-02T12:28:46.308083+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/process_iris_data.py', '--cfg-path', '/tmp/tmp40y8cx0g', '--error-file', '/tmp/tmpititt1re']
[2022-07-02 12:28:47,579] {standard_task_runner.py:80} INFO - Job 51: Subtask _process_flowers_data
[2022-07-02 12:28:47,679] {task_command.py:370} INFO - Running <TaskInstance: process_flowers_dag._process_flowers_data manual__2022-07-02T12:28:46.308083+00:00 [running]> on host a5e5aec483b5
[2022-07-02 12:28:47,811] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=process_flowers_dag
AIRFLOW_CTX_TASK_ID=_process_flowers_data
AIRFLOW_CTX_EXECUTION_DATE=2022-07-02T12:28:46.308083+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-02T12:28:46.308083+00:00
[2022-07-02 12:28:47,812] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/process_iris_data.py", line 29, in _process_flowers_data
    df = pd.read_json(f"{FILES_BASE_PATH}/{USERS_JSON_FILENAME}", orient ='index')
NameError: name 'USERS_JSON_FILENAME' is not defined
[2022-07-02 12:28:47,823] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=process_flowers_dag, task_id=_process_flowers_data, execution_date=20220702T122846, start_date=20220702T122847, end_date=20220702T122847
[2022-07-02 12:28:47,840] {standard_task_runner.py:97} ERROR - Failed to execute job 51 for task _process_flowers_data (name 'USERS_JSON_FILENAME' is not defined; 4001)
[2022-07-02 12:28:47,869] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-02 12:28:47,935] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
